### PR TITLE
fix zombification on Drop on unix

### LINKED ISSUE #32: `Child` does not reap child process on drop
just using stdout as stream doesn't seem to work at all.
That results in a defunct process immediately with stdout stream closed. 

So i'm selecting over the child as well. That gives me all the output and the process is reaped when it closes itself.

However, when the stream is dropped before the child is done, it is not killed.

Instead it will later die when it writes again. then kill is called but the process goes defunct (this seems to be an unrelated problem, since strace tells me waitpid is called correctly).

```rust
        use std::process::{Stdio, Command};
        use tokio_io::codec::{FramedRead, LinesCodec};
        use tokio_process::CommandExt;

        let mut c = Command::new("journalctl")
            .arg("-f")
            .stdout(Stdio::piped())
            .spawn_async(&self.handle)
            .expect("command failed to start");

        let stdout = c.stdout().take().unwrap();
        let stream = FramedRead::new(stdout, LinesCodec::new()).map(|line| {
            psiproto::v1::SyslogEntry{
                log: line,
            }
        }).map_err(|_e| {
            tower_grpc::Error::Protocol(tower_grpc::ProtocolError::Internal)
        });

        let stream = c.into_stream().filter_map(|_|None).map_err(|_e| {
            tower_grpc::Error::Protocol(tower_grpc::ProtocolError::Internal)
        }).select(stream);

        future::ok(Response::new(Box::new(stream)))

```

### PR DESCRIPTION
**Pull request by aep**
fixes #32

call waitpid blocking after kill.
Otherwise the process will never be reaped, because the code to reap it is already dropped.

SIGKILL cannnot be caught, so the process will definitely exit immediately.
We're not waiting for the process itself but for the kernel to execute the kill.

### CODE REVIEW

File: src/unix.rs [hunk 1]
```diff
@@ -90,7 +90,11 @@ impl Child {
         if self.reaped {
             Ok(())
         } else {
-            self.inner.kill()
+            self.inner.kill()?;
+            let mut status = 0;
+            let id = self.id() as c_int;
+            unsafe { libc::waitpid(id, &mut status, 0) };
```
Comment (ipetkov) [inline src/unix.rs]: * `waitpid` can be interrupted, so we should at least retry on `EINTR` here similar to what we do in [`try_wait`](https://github.com/alexcrichton/tokio-process/blob/ec5df8afb274202864148c20e8d3400fbdc35b55/src/unix.rs#L119-L139).
* Also, could you put a small comment, for posterity, to explain why we expect `waitpid` to return quickly

Comment (alexcrichton) [reply src/unix.rs]: I think we'll also want to be sure to set `reaped` to `true` to ensure that we don't reuse the pid as well
